.TH GPKG 1
.SH NAME
gpkg \- source code based package management system
.SH SYNOPSIS
.B gpkg
.I "[options]"
.P
.SH "DESCRIPTION"
This manual page documents briefly the
.BR gpkg 
program.
.PP
gpkg is a source code based package manage system. it use a simple bash script interface to fetch software package information, then it can download software source code from upstream, verify it, uncompress, config, build, record packge files, and install to system autometically. it has rich set of features, especially for Xiange GNU/Linux system or LFS GNU/Linux system.
.PP
features:
.PP
1. record config information
.P
2. record all files

.B aafire
displays burning ascii art flames.
.PP
.B aainfo
displays information about what drivers aalib will use for the display,
keyboard, and mouse, and what parameters, such as screen size those drivers
will use.
.PP
.B aasavefont
saves a font to a file.
.PP
.B aatest
tests the capabilities of aalib.
.SH AUTHOR
This program was written by Lihui Zhang <swordhuihui@gmail.com>,
for the Xiange GNU/Linux system.
