#!/bin/bash

#
# gpkg -- UI program for Xiange Linux package management system 
# 
# by Zhang Lihui <swordhuihui@gmail.com>, 2010-04-13, 15:58
#

#path define
#XGPATH=/var/xiange
XGPATH=..
XGPATH_TOOLS=$XGPATH/tools
XGPATH_LIB=$XGPATH/xglibs
XGPATH_SOURCE=$XGPATH/sources
XGPATH_UNPACK=/tmp/xiange/sources
XGPATH_DEST=/tmp/xiange/pack

#
# version and  usage 
#
gpkg_version=0.10.0
gpkg_usage="
gpkg $gpkg_version, usage:\n
	\t-v            \t\tshow current version\n
	\t-s package 	\tsearch package\n
	\t-d package 	\tdownload package\n
	\t-i package 	\tinstall package\n
	\t-D package 	\tremove package\n
	\n
XianGe base is at $XGPATH\n
"

gpkg_show_usage()
{
	echo -e $gpkg_usage
}

#
# string functions
#

#check: if $2 in $1, return 1, else return 0
str_isIn()
{
	if [ "${1/$2/}" != "${1}" ]; then
		return 1
	else
		return 0
	fi
}

#
# version control
#

#parse atom to $N, $V, $R, 
#by tomgrean @ LinuxSir, 2009-09-11, 20:02
atom_parse()
{
	local ATOM
	local RR

	ATOM="${1%.xgb}"
	RR="${ATOM%-r[0-9]*}"
	R="${ATOM#$RR}"
	V="${RR##*-}"
	N="${RR%$V}"
	N="${N%-}"
}

#compare 2 versions, such 2.6.9 and 2.6.10
#return 0 if same. 
#return 1 if $1 is grater than $2 
#return 2 if $1 is lesser then $2
#by lastart @ LinuxSir
atom_vercmp()
{
	v1=$1.
	v2=$2.
	while true
	do
		a=${v1%%.*}
		b=${v2%%.*}
		[ -z "$a" ] && [ -z "$b" ] &&  return 0
		[ "$a"0 -gt "$b"0 ] && return 1
		[ "$a"0 -lt "$b"0 ] && return 2
		v1="${v1#*.}"
		v2="${v2#*.}"
	done
}

#compare 2 atoms, such as linux-2.6.9.xgb and linux-2.6.10.xgb
#return 0 if same. 
#return 1 if $1 is grater than $2 
#return 2 if $1 is lesser then $2
atom_cmp()
{
	local R1
	local V1
	local N1

	#echo "Begin Compare: $1 $2"

	atom_parse $1
	R1=$R
	V1=$V
	N1=$N
	#echo "N1=$N1, V1=$V1, R1=$R1"

	atom_parse $2
	#echo "N2=$N, V2=$V, R2=$R"

	#compare version
	atom_vercmp $V1 $V
}


#
# search packages
#

#list all pack types
gpkg_get_types()
{
	gpkg_types=`ls $XGPATH_LIB 2>/dev/null`
}

gpkg_get_packages()
{
	gpkg_packs=`ls $XGPATH_LIB/$1 2>/dev/null`
}

#Get Newest file in $XGPATH_LIB/$1
gpkg_getnewest()
{
	local files
	local file
	newest=""

	files=`ls $XGPATH_LIB/$1 2>/dev/null`
	for file in $files
	do
		if [ -z $newest ]; then
			newest=$file
			#echo "First is $file"
		else
			#compare 
			#echo "compare $file $newest"
			atom_cmp $file $newest
			[ "$?" == "1" ] && newest=$file
			#echo "after compare: new=$newest"

		fi
	done
}


#find one packge $1 is type, $2 is package name, $3 is index
gpkg_searchOK()
{
	#show it.
	echo "* $1/$2"

	#get newest version
	gpkg_getnewest $1/$2
	atom_parse $newest
	echo -e "\tAvailable:\t $V$R"

	#search installed
	echo -e "\tInstalled:\t None"

	#add blank line
	echo ""
}

gpkg_search()
{
	local type
	local pack
	local count=0

	gpkg_get_types
	for type in $gpkg_types
	do
		gpkg_get_packages $type
		for pack in $gpkg_packs
		do
			str_isIn $pack $1
			if [ $? == 1 ]; then
				#find one.
				count=$(($count + 1))
				gpkg_searchOK $type $pack $count
			fi
		done
	done
	echo "search $1, result count $count"
}


#
# download packet
#

#check and download package, $1 is URL, $2 is local file name.
check_and_download_raw()
{
	local fname=$2
	local retry

	#retry 3 times
	for((retry=0; retry<3; retry++))
	do
		#check if package has already exist.
		if [ -f ${XGPATH_SOURCE}/${fname} ]; then
			printf "%s exists, Skip.\n" $fname
			return 0
		else
			printf "downloading from %s, retry %d...\n" ${1} ${retry}
			rm -f ${XGPATH_SOURCE}/${fname}.tmp
			wget $1 -O ${XGPATH_SOURCE}/${fname}.tmp
			if [ "$?" == 0 ]; then
				#download ok.
				mv ${XGPATH_SOURCE}/${fname}.tmp ${XGPATH_SOURCE}/${fname}
				return 0
			fi
		fi
	done

	printf "down load failed, quit.\n"
	return 1
}

#check and download package, $1 is URL.
check_and_download()
{
	local fname=${1##*/}

	#call raw mode.
	check_and_download_raw $1 $fname
}


gpkg_begin_download()
{
	local url
	local ret=0

	#echo "Found $1/$2"

	#find newest version.
	gpkg_getnewest $1/$2
	echo $newest
	atom_parse $newest

	echo "Begin download $N-$V$R..."

	#include package build scripts
	. $XGPATH_LIB/$1/$2/$newest

	#init build script file
	xgb_init

	#download all files
	for url in ${SRC_URI}
	do
		#echo $url
		check_and_download $url
		ret=$?
		[ $ret != 0 ] && break
	done

	#check
	[ $ret == 0 ] && echo "Download OK"
	return $ret
}

gpkg_download()
{
	local type
	local pack
	local count=0
	local -a retType
	local -a retPack

	gpkg_get_types
	for type in $gpkg_types
	do
		gpkg_get_packages $type
		for pack in $gpkg_packs
		do
			if [ $1 == $pack ]; then
				#find 
				retType[$count]=$type
				retPack[$count]=$pack
				count=$(($count + 1))
			fi
		done
	done
	
	#check result.
	if [ "$count" == "0" ]; then
		#not found
		echo "Not Found"
		return 1
	fi

	if [ "$count" == "1" ]; then
		#OK, begin download
		gpkg_begin_download ${retType[0]} ${retPack[0]}
		return 
	fi

	#find more, show and select.
	echo "More result, $count, please select 1"

	unset retType
	unset retPack

}

#
# Install package
#
gpkg_install()
{
	#find xgb file

	#call init

	#call unpack

	#call config

	#call build

	#call install

	#make package

	#call post_install
	return 0
}

#
# parse parameters
#
case "${1}" in
-v)
	#show version.
	echo $gpkg_version
	;;

-s)
	#search package.
	gpkg_search $2
	;;

-d)
	gpkg_download $2
	#download
	;;

-i)
	gpkg_install $2
	;;

*)
	#show usage 
	gpkg_show_usage
	exit 0
	;;
esac


